In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

# Ans :
arr1_copy = np.copy(arr1)
arr1_copy[:,[0,3]] = arr1_copy[:,[3,0]]
arr1_copy

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

# Ans:
np.flip(arr1,axis=0)

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

# Ans:
arr2[np.isnan(arr2)] = np.nanmean(arr2)
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[19,  5, 47, 62],
       [96, 16, 54, 92],
       [20, 85, 12, 77],
       [27, 31,  6, 91],
       [70, 37, 20, 73]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

# Ans:
mask1 = np.where(arr3 > 25)
mask2 = np.where(arr3 % 3 == 0)

arr3[mask1 or mask2]

array([47, 62, 96, 54, 92, 85, 77, 27, 31, 91, 70, 37, 73])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

# Ans:
tenth = np.percentile(arr3,10)
quarter = np.percentile(arr3,25)
medn = np.percentile(arr3,50)

print("10th : ",tenth,"\n25th : ",quarter,"\n50th : ",medn)

# Verifying
print("\nVerifying 50th percentile\nMedian : ",np.median(arr3))

10th :  11.4
25th :  19.75
50th :  42.0

Verifying 50th percentile
Median :  42.0